### ISSUE TITLE
Installation fails - pyqt5 dependency

### ISSUE THREAD

**Issue by juushya** [VainlyStrain/Vailyn#2]
**Category**
Installation issue on Kali

**Describe the bug**
Installation fails due to pyqt5 dependency

**To Reproduce**
1. `pip install -r requirements.txt`
2. See error below:

```
root@kali:/opt/Vailyn# pip install -r requirements.txt 
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting treelib
  Using cached treelib-1.6.1.tar.gz (24 kB)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (2.18.4)
Requirement already satisfied: argparse in /usr/lib/python2.7 (from -r requirements.txt (line 3)) (1.2.1)
Requirement already satisfied: colorama in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (0.4.3)
ERROR: Could not find a version that satisfies the requirement PyQt5 (from -r requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for PyQt5 (from -r requirements.txt (line 5))
```

**Expected behaviour**
Clean installation is expected.

**Desktop**
 - OS: Kali Linux 
```
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.3
Codename:       kali-rolling

Linux kali 5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux
```

 - Python Version - 2.7.18
 - pip 20.2

**Comment by VainlyStrain** [comment]
Hi! First of all, sorry for the inconvenience.

Vailyn only works with relatively new versions of Python 3 (it has been officially tested with 3.7 and 3.8, but it should work with 3.6 too).

The error you are getting probably means that they have retired the package from the Python2 repos. However, even if it would succeed, Vailyn would not run due to the major changes between Python 2 and 3.

Please, try to repeat the installation with Python 3, and report back if it works. The commands should be either `pip3` or `python3 -m pip`.

Greetings!

Edit: above reason is correct, the makers of PyQt5 have dropped support for Python < 3.5. So, using above commands should resolve the issue.

**Comment by juushya** [comment]
Yeah, this works with python3 only. Here's how I got it running:

Install pip3
```
# apt install python3-pip
```
Install requirements (pyqt5)
```
root@kali:/opt/Vailyn# python3 -m pip install -r requirements.txt 
Collecting treelib
  Using cached treelib-1.6.1.tar.gz (24 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.23.0)
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (0.4.3)
Requirement already satisfied: PyQt5 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (5.15.0)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from treelib->-r requirements.txt (line 1)) (0.18.2)
Building wheels for collected packages: treelib
  Building wheel for treelib (setup.py) ... done
  Created wheel for treelib: filename=treelib-1.6.1-py3-none-any.whl size=18371 sha256=0e18384f47128dd6250d79c68a8dc2f97a6fa5eb71c608be626ac1774e422d7f
  Stored in directory: /root/.cache/pip/wheels/71/df/8b/6b005e3bb9b275c24dfc392cda334f43f132e85a6f17cfad3a
Successfully built treelib
Installing collected packages: treelib, argparse
Successfully installed argparse-1.4.0 treelib-1.6.1
```

Running Vailyn
`python3 Vailyn -h` <--- works only with python3, throws a traceback with python2.x

Cheers~

**Comment by juushya** [comment]
It seems QT may not work. Here's a screenshot of a query attack (I hope this is correct config):

![image](https://user-images.githubusercontent.com/4639200/89129076-f33c4980-d517-11ea-9f84-8b6a9140ea7f.png)

![image](https://user-images.githubusercontent.com/4639200/89128990-20d4c300-d517-11ea-969e-335f61ff313d.png)

**Comment by VainlyStrain** [comment]
It seems like a style sheet issue. Will take a look at it.

Greetings

**Comment by VainlyStrain** [comment]
Just a question: is the grey part in the first picture part of the issue, or is it applied to censor the IP/port?

**Comment by VainlyStrain** [comment]
should be fixed in the latest commit. Let me know if the issue persists, and I'll open the issue again :)

**Comment by juushya** [comment]
The grey part in the first pic is just a censor. The second pic shows the actual issue. I'll pull the latest version, and give this a shot. Thanks.
