### ISSUE TITLE
[BUG] Problem running on macOS ModuleNotFoundError: No module named 'dbus'

### ISSUE THREAD

**Issue by thistehneisen** [VainlyStrain/Vailyn#24]
**Category**
Other

**Describe the bug**
```
➜  Vailyn git:(master) ./Vailyn
Traceback (most recent call last):
  File "/Users/nils.putnins/Code/Python/Vailyn/./Vailyn", line 26, in <module>
    from core.Cli import cli_main
  File "/Users/nils.putnins/Code/Python/Vailyn/core/Cli.py", line 59, in <module>
    from core.methods.attack import (
  File "/Users/nils.putnins/Code/Python/Vailyn/core/methods/attack.py", line 51, in <module>
    from core.methods.notify import notify
  File "/Users/nils.putnins/Code/Python/Vailyn/core/methods/notify.py", line 29, in <module>
    import notify2
  File "/usr/local/lib/python3.9/site-packages/notify2.py", line 39, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Install requirements and try to run on OS X (iTerm)

**Desktop (please complete the following information):**
 - macOS Big Sur

**Comment by VainlyStrain** [comment]
Hi!

I'm sorry, I currently don't have a macOS Big Sur machine to test it on, but apparently, this resolves the issue:

```
pip install dbus-python
```

Please let me know if it works for you. If not, I'll exclude the notify2 functionality in the MacOS version.
Alternatively to the additional pip module, you can set the following in `core/config.py`:

```
DESKTOP_NOTIFY = False
```

However, this will disable the notification functionality entirely, so if you want to use that feature, solution 1 is the preferable one.

Greetings!

**Comment by thistehneisen** [comment]
Unfortunately the setup with `pip install dbus-python` fails, even when dbus itself is set up via `brew install dbus` and `brew service start dbus` beforehand. Setting `DESKTOP_NOTIFY = False` in the `core/config.py` still outputs the same requirement error.

**Comment by djhashh** [comment]
Ditto

**Comment by VainlyStrain** [comment]
Hi,

Could you please provide the output of the following command:

```
$ python -c "import sys; print(sys.platform)"
```

? Thanks!

**Comment by VainlyStrain** [comment]
This should be fixed properly now. Could you please confirm if it works for you?
